In [26]:
import tensorflow as tf

# 예제 데이터 (questions는 인코더 입력, answers는 디코더 입력/출력)
questions = tf.constant([
    [1, 2, 3, 4, 0, 0],  # 패딩 토큰 0 사용
    [5, 6, 7, 0, 0, 0],
    [8, 9, 0, 0, 0, 0]
])

answers = tf.constant([
    [11, 12, 13, 14, 0, 0],  # 실제 출력 시퀀스
    [15, 16, 17, 0, 0, 0],
    [18, 19, 0, 0, 0, 0]
])

# Dataset 생성
dataset = tf.data.Dataset.from_tensor_slices((
    {
        'inputs': questions,
        'dec_inputs': answers[:, :-1]  # 디코더의 입력. 마지막 패딩 토큰이 제거됨
    },
    {
        'outputs': answers[:, 1:]  # 디코더의 실제 출력. 첫 번째 시작 토큰이 제거됨
    }
))

# 배치 크기를 2로 설정하여 데이터셋을 배치로 나눔
dataset = dataset.batch(2)
dataset

<_BatchDataset element_spec=({'inputs': TensorSpec(shape=(None, 6), dtype=tf.int32, name=None), 'dec_inputs': TensorSpec(shape=(None, 5), dtype=tf.int32, name=None)}, {'outputs': TensorSpec(shape=(None, 5), dtype=tf.int32, name=None)})>

In [27]:
batch = dataset.take(1)
# batch

In [28]:
inputs, targets = batch
inputs, targets

ValueError: not enough values to unpack (expected 2, got 1)

In [20]:
batch = dataset.take(1)
batch

<_TakeDataset element_spec=({'inputs': TensorSpec(shape=(None, 6), dtype=tf.int32, name=None), 'dec_inputs': TensorSpec(shape=(None, 5), dtype=tf.int32, name=None)}, {'outputs': TensorSpec(shape=(None, 5), dtype=tf.int32, name=None)})>

In [30]:

# `take(1)`을 사용하여 배치 하나를 가져와서 확인
for batch in dataset.take(3):
    print("======================================")
    inputs, targets = batch
    print("Encoder Inputs:")
    print(inputs['inputs'].numpy())
    print("\nDecoder Inputs (for Teacher Forcing):")
    print(inputs['dec_inputs'].numpy())
    print("\nDecoder Outputs (Actual Outputs):")
    print(targets['outputs'].numpy())


Encoder Inputs:
[[1 2 3 4 0 0]
 [5 6 7 0 0 0]]

Decoder Inputs (for Teacher Forcing):
[[11 12 13 14  0]
 [15 16 17  0  0]]

Decoder Outputs (Actual Outputs):
[[12 13 14  0  0]
 [16 17  0  0  0]]
Encoder Inputs:
[[8 9 0 0 0 0]]

Decoder Inputs (for Teacher Forcing):
[[18 19  0  0  0]]

Decoder Outputs (Actual Outputs):
[[19  0  0  0  0]]


In [31]:
len(dataset.take(3))

2